language: java

script:
  - mvn clean
  - mvn test -B

before_deploy:
  - mvn package -DskipTests=true

deploy:
  provider: cloudfoundry
  username: $PCF_USERNAME
  password: $PCF_PASSWORD
  api: $PCF_API
  organization: $PCF_ORG
  space: $PCF_SPACE
  manifest: manifest.yml # (optional)  Defaults to manifest.yml.
  app_name: ah-poc-sapi-cc-bal # (optional)

after_deploy:
  - git clone https://github.com/zuhlke/ah-poc-papi-springboot.git
  - cd ah-poc-papi-springboot/contract-tests
  - ./bin/ah-poc-sapi-cc-bal